openapi: 3.1.0
info:
  title: Meta Ads API - Campanhas
  version: '1.0.0'
  description: Endpoints específicos para gestão e análise de campanhas do Meta Ads

paths:
  /act_{ad_account_id}/campaigns:
    get:
      operationId: listCampaigns
      summary: Lista todas as campanhas da conta
      description: Retorna a lista de campanhas com métricas básicas de performance
      parameters:
        - $ref: '../main.yaml#/components/parameters/adAccountId'
        - name: fields
          in: query
          required: false
          schema:
            type: string
          description: Campos a serem retornados
          example: "id,name,objective,status,daily_budget,lifetime_budget,start_time,end_time"
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 1000
          description: Número máximo de campanhas a retornar
          example: 25
      responses:
        '200':
          description: Lista de campanhas retornada com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CampaignList'
        '401':
          $ref: '../main.yaml#/components/schemas/Error'
        '403':
          $ref: '../main.yaml#/components/schemas/Error'

  /act_{ad_account_id}/insights:
    get:
      operationId: getCampaignInsights
      summary: Obtém insights das campanhas
      description: Retorna métricas detalhadas de performance das campanhas
      parameters:
        - $ref: '../main.yaml#/components/parameters/adAccountId'
        - $ref: '../main.yaml#/components/parameters/datePreset'
        - $ref: '../main.yaml#/components/parameters/timeIncrement'
        - name: level
          in: query
          required: false
          schema:
            type: string
            enum: [account, campaign, adset, ad]
          description: Nível de agregação dos dados
          example: campaign
        - name: fields
          in: query
          required: false
          schema:
            type: string
          description: Métricas a serem retornadas
          example: "impressions,reach,spend,clicks,ctr,cpc,actions"
        - name: breakdowns
          in: query
          required: false
          schema:
            type: string
            enum: [publisher_platform, platform_position, age, gender, region]
          description: Dimensões para segmentação dos dados
          example: "platform_position"
      responses:
        '200':
          description: Insights retornados com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InsightsResponse'
        '401':
          $ref: '../main.yaml#/components/schemas/Error'
        '403':
          $ref: '../main.yaml#/components/schemas/Error'

components:
  schemas:
    Campaign:
      type: object
      properties:
        id:
          type: string
          description: ID da campanha
        name:
          type: string
          description: Nome da campanha
        objective:
          type: string
          description: Objetivo da campanha
        status:
          type: string
          enum: [ACTIVE, PAUSED, DELETED, ARCHIVED]
          description: Status atual da campanha
        daily_budget:
          type: number
          format: float
          description: Orçamento diário em BRL
        lifetime_budget:
          type: number
          format: float
          description: Orçamento total da campanha em BRL
        start_time:
          type: string
          format: date-time
          description: Data de início da campanha
        end_time:
          type: string
          format: date-time
          description: Data de término da campanha

    CampaignList:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/Campaign'
        paging:
          type: object
          properties:
            cursors:
              type: object
              properties:
                before:
                  type: string
                after:
                  type: string
            next:
              type: string
              format: uri

    InsightsResponse:
      type: object
      properties:
        data:
          type: array
          items:
            type: object
            properties:
              date_start:
                type: string
                format: date
              date_stop:
                type: string
                format: date
              campaign_id:
                type: string
              campaign_name:
                type: string
              impressions:
                type: integer
                description: Total de impressões
                example: 69488
              reach:
                type: integer
                description: Alcance único
                example: 33992
              spend:
                type: number
                format: float
                description: Investimento em BRL
              clicks:
                type: integer
                description: Total de cliques
              ctr:
                type: number
                format: float
                description: Taxa de cliques (%)
              cpc:
                type: number
                format: float
                description: Custo por clique em BRL
              actions:
                type: array
                items:
                  type: object
                  properties:
                    action_type:
                      type: string
                      enum: [like, comment, post_save]
                    value:
                      type: integer
              video_p25_watched_actions:
                type: array
                items:
                  type: object
                  properties:
                    action_type:
                      type: string
                      enum: [video_view]
                    value:
                      type: integer
              video_p50_watched_actions:
                type: array
                items:
                  type: object
                  properties:
                    action_type:
                      type: string
                      enum: [video_view]
                    value:
                      type: integer
              video_p75_watched_actions:
                type: array
                items:
                  type: object
                  properties:
                    action_type:
                      type: string
                      enum: [video_view]
                    value:
                      type: integer
              video_p95_watched_actions:
                type: array
                items:
                  type: object
                  properties:
                    action_type:
                      type: string
                      enum: [video_view]
                    value:
                      type: integer
              video_avg_time_watched_actions:
                type: array
                items:
                  type: object
                  properties:
                    action_type:
                      type: string
                      enum: [video_view]
                    value:
                      type: number
                      format: float
                      description: Tempo médio de visualização em segundos
              platform_position:
                type: string
                enum: [instagram_stories, instagram_reels, instagram_feed]
                description: Posição do anúncio
              publisher_platform:
                type: string
                enum: [instagram]
                description: Plataforma de publicação
        paging:
          type: object
          properties:
            cursors:
              type: object
              properties:
                before:
                  type: string
                after:
                  type: string
            next:
              type: string
              format: uri
