openapi: 3.1.0
info:
  title: Meta Ads API Connector
  version: '1.0.0'
  description: |
    Conector para Meta Ads API v22.0 com gerenciamento automático de autenticação.
    Suporta autenticação via System User Token e Page Token com troca automática.

servers:
  - url: https://graph.facebook.com/v22.0
    description: Meta Graph API v22.0

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Meta Access Token (System User Token ou Page Token)

  schemas:
    Error:
      type: object
      properties:
        error:
          type: object
          properties:
            message:
              type: string
              description: Mensagem de erro detalhada
            type:
              type: string
              description: Tipo do erro
            code:
              type: integer
              description: Código do erro
            error_subcode:
              type: integer
              description: Subcódigo do erro
            fbtrace_id:
              type: string
              description: ID de rastreamento do erro

    TokenResponse:
      type: object
      properties:
        access_token:
          type: string
          description: Token de acesso gerado
        token_type:
          type: string
          enum: [bearer]
        expires_in:
          type: integer
          description: Tempo de expiração em segundos

  parameters:
    adAccountId:
      name: ad_account_id
      in: path
      required: true
      schema:
        type: string
      description: ID da conta de anúncios (ex: act_906594379912215)
      example: act_906594379912215

    pageId:
      name: page_id
      in: path
      required: true
      schema:
        type: string
      description: ID da página do Facebook
      example: "102264027940184"

    datePreset:
      name: date_preset
      in: query
      required: false
      schema:
        type: string
        enum: [today, yesterday, this_week, last_week, this_month, last_month, last_3d, last_7d, last_30d]
      description: Período predefinido para análise
      example: last_7d

    timeIncrement:
      name: time_increment
      in: query
      required: false
      schema:
        type: integer
        enum: [1, 7, 28, 30]
      description: Incremento de tempo para agregação de dados
      example: 1

paths:
  /oauth/access_token:
    get:
      operationId: getSystemToken
      summary: Obtém um System User Token
      description: Gera um token de sistema usando client credentials
      parameters:
        - name: client_id
          in: query
          required: true
          schema:
            type: string
          example: "1660695328664197"
        - name: client_secret
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Token gerado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'
        '400':
          description: Erro na requisição
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /{page_id}:
    get:
      operationId: getPageToken
      summary: Obtém um Page Access Token
      description: Obtém o token de acesso para uma página específica
      parameters:
        - $ref: '#/components/parameters/pageId'
        - name: fields
          in: query
          required: true
          schema:
            type: string
          example: "access_token"
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Token da página obtido com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                    description: Token de acesso da página
        '401':
          description: Erro de autenticação
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Erro de permissão
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

security:
  - bearerAuth: []
