openapi: 3.1.0
info:
  title: Meta Ads API Configuration
  version: '1.0.0'
  description: Configuração central para o conector Meta Ads

x-meta-config:
  api-version: v22.0
  base-url: https://graph.facebook.com/v22.0
  fixed-ids:
    client-id: "1660695328664197"
    page-id: "102264027940184"
    account-id: "act_906594379912215"
  metrics:
    stories:
      cpm: 17.94
      engagement-rate: 18.43
      retention-50: 57.8
      retention-95: 24.1
      avg-time: 3.0
    reels:
      cpm: 7.20
      engagement-rate: 31.16
      retention-50: 43.1
      retention-95: 18.3
      avg-time: 4.0
  breakdowns:
    - publisher_platform
    - platform_position
    - age
    - gender
    - region
  date-presets:
    - today
    - yesterday
    - this_week
    - last_week
    - this_month
    - last_month
    - last_3d
    - last_7d
    - last_30d
  time-increments:
    - 1
    - 7
    - 28
    - 30
