openapi: 3.1.0
info:
  title: Meta Ads API Connector
  version: '1.0.0'
  description: Conector para Meta Ads API v22.0

servers:
  - url: https://graph.facebook.com/v22.0
    description: Meta Graph API v22.0

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Error:
      type: object
      properties:
        error:
          type: object
          properties:
            message:
              type: string
            code:
              type: integer
            type:
              type: string

    TokenResponse:
      type: object
      properties:
        access_token:
          type: string
        token_type:
          type: string
          enum: [bearer]
        expires_in:
          type: integer

    Campaign:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        status:
          type: string
          enum: [ACTIVE, PAUSED, DELETED, ARCHIVED]
        daily_budget:
          type: number
        lifetime_budget:
          type: number

    Insights:
      type: object
      properties:
        date_start:
          type: string
          format: date
        date_stop:
          type: string
          format: date
        impressions:
          type: integer
          example: 69488
        reach:
          type: integer
          example: 33992
        spend:
          type: number
        ctr:
          type: number
        cpc:
          type: number

paths:
  /oauth/access_token:
    get:
      operationId: getSystemToken
      summary: Obtém token de sistema
      parameters:
        - name: client_id
          in: query
          required: true
          schema:
            type: string
          example: "1660695328664197"
        - name: client_secret
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Token gerado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'
        '400':
          description: Erro na requisição
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /act_{ad_account_id}/campaigns:
    get:
      operationId: listCampaigns
      summary: Lista campanhas
      parameters:
        - name: ad_account_id
          in: path
          required: true
          schema:
            type: string
          example: "act_906594379912215"
        - name: fields
          in: query
          schema:
            type: string
          example: "id,name,status,daily_budget"
      responses:
        '200':
          description: Campanhas listadas com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Campaign'
                  paging:
                    type: object
                    properties:
                      cursors:
                        type: object
                        properties:
                          before:
                            type: string
                          after:
                            type: string
        '401':
          $ref: '#/components/schemas/Error'

  /act_{ad_account_id}/insights:
    get:
      operationId: getCampaignInsights
      summary: Obtém insights das campanhas
      parameters:
        - name: ad_account_id
          in: path
          required: true
          schema:
            type: string
          example: "act_906594379912215"
        - name: date_preset
          in: query
          schema:
            type: string
            enum: [today, yesterday, last_3d, last_7d, last_30d]
          example: "last_7d"
        - name: fields
          in: query
          schema:
            type: string
          example: "impressions,reach,spend,ctr,cpc"
        - name: breakdowns
          in: query
          schema:
            type: string
            enum: [publisher_platform, platform_position, age, gender, region]
      responses:
        '200':
          description: Insights obtidos com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Insights'
                  paging:
                    type: object
                    properties:
                      cursors:
                        type: object
                        properties:
                          before:
                            type: string
                          after:
                            type: string
        '401':
          $ref: '#/components/schemas/Error'

security:
  - bearerAuth: []
